version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: transmission_server_1
      APP_PORT: 9091

  server:
    image: linuxserver/transmission:4.0.4@sha256:760b2d364dbfb6d84c9688f624dc48f98665b15e9e41be2170715afcc525e329
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    ports:
      - 51413:51413
      - 51413:51413/udp
    restart: on-failure

  widget-server:
    image: getumbrel/umbrel-transmission-widget-server:v1.0.0@sha256:db39ed3471686bf2b900dfa568f41d31c0b2a7fbc4df632e61b583c6978ba686
    environment:
      - TRANSMISSION_URL=http://transmission_server_1
      - TRANSMISSION_PORT=9091
    restart: on-failure
