name: Lint apps

on:
  pull_request:
    branches:
      - master

jobs:
  lint-apps:
    name: Lint apps
    runs-on: ubuntu-latest
    steps:
      - uses: sharknoon/umbrel-app-linter-action@0e2fb2038f8fd2e839887b232f6310fc6bc0edf4
